version: '3'

services:
  solarx-gui:
    container_name: gui

    build:
      context: ./frontend-gui
      dockerfile: Dockerfile.dev

    command: npm run start

    ports:
      - 3000:3000
    
    volumes:
      - ./frontend-gui/src:/app/src


  solarx-backend:
    container_name: backend
    hostname: backend
    build:
      context: ./kafka-websocket
      dockerfile: Dockerfile.dev

    command: npm run dev

    ports:
      - 8000:8000
    
    volumes:
      - ./kafka-websocket/src:/app/src

    depends_on:
      - kafka


  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "2181:2181"
      
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper


