version: '3'

services:
  solarx-gui:
    container_name: gui

    build:
      context: ./frontend-gui
      dockerfile: Dockerfile.dev
      

    command: npm run start

    ports:
      - 3000:3000
    
    volumes:
      - ./frontend-gui/src:/app/src


  solarx-backend:
    container_name: backend

    build:
      context: ./kafka-websocket
      dockerfile: Dockerfile.dev
      

    command: npm run dev

    ports:
      - 8000:8000
    
    volumes:
      - ./kafka-websocket/src:/app/src

