services:
  solarx-gui:
    container_name: gui

    build:
      context: ./frontend-gui
      dockerfile: Dockerfile

    command: npm run start

    ports:
      - 3000:3000
    
    volumes:
      - ./frontend-gui/src:/app/src

    networks:
      - solarx-network


  solarx-backend:
    container_name: backend
    hostname: backend
    build:
      context: ./kafka-websocket
      dockerfile: Dockerfile

    command: npm run dev

    # ports:
    #   - 8000:8000
    #   - 8080:8080
    #   - 9090:9090
    #   - 9191:9191


    volumes:
      - ./kafka-websocket/src:/app/src

    depends_on:
      - kafka
      - solarx-python-data-stream

    networks:
      - solarx-network



  solarx-python-data-stream:
    container_name: solarx-python-data-stream
    build:
      context: ./
      dockerfile: Dockerfile


    volumes:
      - ./:/usr/app/src

    depends_on:
      - kafka

    networks:
      - solarx-network

      



  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "2181:2181"
    
    networks:
      - solarx-network
      
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    
    networks:
      - solarx-network


networks:
  solarx-network:
    name: solarx-network
    external: true