version: "3"

services:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0
    container_name: phpmyadmin

    ports:
      - 800:80

    environment:
      - PMA_ARBITRARY=1

    restart: unless-stopped