version: '3'

services:
  solarx-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'solarx'
      MYSQL_USER: 'dyab'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./database-schema:/docker-entrypoint-initdb.d
      - my-db:/var/lib/mysql

volumes:
  my-db: